name: CI

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 13 * * 1"  # Every Monday at 9AM EST

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: Test pre-commit hooks
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pre-commit run -a

  validate-types-and-docstrings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: Setup environment
        run: |
            python -m pip install --upgrade pip
            pip install ".[dev,jeig]"

      - name: mypy type validation
        run: |
            mypy src
            mypy examples

      - name: imports validation
        run: |
            find . -name "*.py" | xargs black --check
            find . -name "*.py" | xargs isort --profile black --check-only

      - name: darglint docstring validation
        run: |
            darglint src --strictness=short --ignore-raise=ValueError
            darglint examples --strictness=short --ignore-raise=ValueError

  test-fmmax:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: pyproject.toml
      - name: Setup environment
        run: |
            python -m pip install --upgrade pip
            pip install ".[dev]"
      - name: Test fmmax
        run: pytest tests/fmmax

  test-fmmax-jeig:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: pyproject.toml
      - name: Setup environment
        run: |
            python -m pip install --upgrade pip
            pip install ".[dev,jeig]"
      - name: Test fmmax
        run: pytest tests/fmmax

  test-grcwa:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: pyproject.toml
      - name: Setup environment
        run: |
            python -m pip install --upgrade pip
            pip install ".[dev]"
      - name: Test grcwa
        run: pytest tests/grcwa

  test-examples:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: pyproject.toml
      - name: Setup environment
        run: |
            python -m pip install --upgrade pip
            pip install ".[dev]"
      - name: Test examples
        run: python -m pytest tests/examples
