name: gym

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-gym:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: install fmmax
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"

      - name: clone invrs-gym
        run: |
          cd ..
          git clone https://github.com/invrs-io/gym
          cd gym
          pytest
